#!/usr/bin/env bash
# gen-roots-header.sh — regenerate src/trust_roots.hpp from signing/roots/r*.pub.der.
#
# Usage (repo root): scripts/trust/gen-roots-header.sh
#
# Replacing root public keys changes what every future binary trusts; see
# docs/signing-trust-model.md §7 before running this for anything but a
# no-op regeneration.

set -euo pipefail

OUT=src/trust_roots.hpp
THRESHOLD=2
ROOTS=(r1 r2 r3)

for r in "${ROOTS[@]}"; do
    f="signing/roots/${r}.pub.der"
    [[ -f "$f" ]] || { echo "ERROR: $f not found (run from repo root)" >&2; exit 1; }
    openssl pkey -pubin -inform DER -in "$f" -text -noout 2>/dev/null \
        | grep -q '^ML-DSA-65 Public-Key' || { echo "ERROR: $f is not ML-DSA-65" >&2; exit 1; }
done

{
    echo '#pragma once'
    echo '// trust_roots.hpp — compiled-in ML-DSA-65 root public keys (threshold 2 of 3).'
    echo '// GENERATED by scripts/trust/gen-roots-header.sh from signing/roots/ — DO NOT EDIT.'
    echo '// See docs/signing-trust-model.md §3. Private seeds are held offline by the owner.'
    echo '#include <array>'
    echo '#include <cstddef>'
    echo '#include <cstdint>'
    echo
    echo 'namespace ntm::trust'
    echo '{'
    echo
    for r in "${ROOTS[@]}"; do
        f="signing/roots/${r}.pub.der"
        n=$(wc -c < "$f" | tr -d ' ')
        echo "// ${r}: sha256 $(openssl dgst -sha256 -r "$f" | cut -c1-64)"
        echo "inline constexpr std::array<std::uint8_t, ${n}> kRoot_${r} = {{"
        od -An -v -tx1 "$f" | awk '{ for (i = 1; i <= NF; i++) printf "%s0x%s", (n++ % 16 ? "," : (n > 1 ? ",\n    " : "    ")), $i } END { print "" }'
        echo '}};'
        echo
    done
    echo 'struct TrustRootEntry'
    echo '{'
    echo '    const char         *id;'
    echo '    const std::uint8_t *der;'
    echo '    std::size_t         len;'
    echo '};'
    echo
    echo "inline constexpr std::size_t kTrustRootThreshold = ${THRESHOLD};"
    echo
    echo "inline constexpr std::array<TrustRootEntry, ${#ROOTS[@]}> kTrustRoots = {{"
    for r in "${ROOTS[@]}"; do
        echo "    {\"${r}\", kRoot_${r}.data(), kRoot_${r}.size()},"
    done
    echo '}};'
    echo
    echo '} // namespace ntm::trust'
} > "$OUT"

echo "[gen-roots-header] wrote $OUT"
