#!/usr/bin/env bash
# manage-build-keys.sh — ML-DSA-65 build-signing key management for ntm-server.
#
# Usage:
#   ./scripts/manage-build-keys.sh          # check or generate key pair
#   ./scripts/manage-build-keys.sh --force  # regenerate key pair (overwrites public key)
#
# Key locations:
#   Private key: ~/.ntm/privatebuildkey.secret  (PEM, mode 600, NEVER committed to repo)
#   Public key:  src/build_pubkey.hpp           (DER bytes, committed to repo)
#
# Algorithm: ML-DSA-65 (CRYSTALS-Dilithium Level 3, NIST FIPS 204)
# Requires:  OpenSSL 3.3+ (ML-DSA-65 support built into default provider since 3.3)
#            xxd (part of vim package on most distros)
#
# This script is idempotent when both key files exist and are valid.
# It NEVER stores the private key anywhere in the repository.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

PRIVATE_KEY_PATH="${HOME}/.ntm/privatebuildkey.secret"
PUBLIC_KEY_HPP="${REPO_ROOT}/src/build_pubkey.hpp"

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
    FORCE=1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "[manage-build-keys] $*"; }

check_openssl() {
    local ver
    ver=$(openssl version 2>/dev/null | grep -oP '\d+\.\d+' | head -1)
    local major minor
    major=$(echo "$ver" | cut -d. -f1)
    minor=$(echo "$ver" | cut -d. -f2)
    if [[ "$major" -lt 3 ]] || { [[ "$major" -eq 3 ]] && [[ "$minor" -lt 3 ]]; }; then
        die "OpenSSL 3.3+ required for ML-DSA-65 support (found: $(openssl version))"
    fi
    # Confirm ML-DSA-65 is available
    if ! openssl list -signature-algorithms 2>/dev/null | grep -q 'ML-DSA-65'; then
        die "ML-DSA-65 not available in this OpenSSL build ($(openssl version))"
    fi
}

validate_private_key() {
    local path="$1"
    [[ -f "$path" ]] || return 1
    openssl pkey -in "$path" -check -noout 2>/dev/null | grep -q 'Key is valid' || return 1
    local algo
    algo=$(openssl pkey -in "$path" -text -noout 2>/dev/null | grep -o 'ML-DSA-[0-9]*' | head -1)
    [[ "$algo" == "ML-DSA-65" ]] || return 1
    return 0
}

generate_keypair() {
    info "Generating ML-DSA-65 key pair..."
    mkdir -p "$(dirname "${PRIVATE_KEY_PATH}")"
    chmod 700 "$(dirname "${PRIVATE_KEY_PATH}")"

    # Generate private key (PEM)
    openssl genpkey -algorithm ML-DSA-65 -out "${PRIVATE_KEY_PATH}" 2>/dev/null
    chmod 600 "${PRIVATE_KEY_PATH}"
    info "Private key written to: ${PRIVATE_KEY_PATH}"
}

write_public_key_hpp() {
    info "Writing public key to: ${PUBLIC_KEY_HPP}"

    # Export DER-encoded SubjectPublicKeyInfo (1974 bytes for ML-DSA-65)
    local der_bytes
    der_bytes=$(openssl pkey -in "${PRIVATE_KEY_PATH}" -pubout -outform DER 2>/dev/null | xxd -i | \
        sed 's/unsigned char .*\[\] = {//' | sed 's/};//' | tr -d '\n ')

    local der_len
    der_len=$(openssl pkey -in "${PRIVATE_KEY_PATH}" -pubout -outform DER 2>/dev/null | wc -c)

    cat > "${PUBLIC_KEY_HPP}" << EOF
#pragma once
// build_pubkey.hpp — ML-DSA-65 (NIST FIPS 204) public key for server binary verification.
// Generated by scripts/manage-build-keys.sh — DO NOT EDIT BY HAND.
// The corresponding private key is stored at ~/.ntm/privatebuildkey.secret (never in repo).
// Algorithm: ML-DSA-65 (Dilithium Level 3), key format: SubjectPublicKeyInfo DER.
#include <array>
#include <cstdint>

namespace ntm::signing
{

// DER-encoded ML-DSA-65 SubjectPublicKeyInfo public key (${der_len} bytes).
// Used by verifyServerSignature() at startup to validate the server binary.
inline constexpr std::array<std::uint8_t, ${der_len}> kBuildPublicKeyDer = {{
    ${der_bytes}
}};

} // namespace ntm::signing
EOF
    info "Public key header written (${der_len} bytes DER)."
}

# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

check_openssl

HAVE_PRIVATE=0
HAVE_PUBLIC=0

[[ -f "${PRIVATE_KEY_PATH}" ]] && validate_private_key "${PRIVATE_KEY_PATH}" && HAVE_PRIVATE=1
[[ -f "${PUBLIC_KEY_HPP}" ]] && HAVE_PUBLIC=1

if [[ "$FORCE" -eq 1 ]]; then
    info "--force: regenerating key pair."
    generate_keypair
    write_public_key_hpp
    info "Done. Commit src/build_pubkey.hpp to the repository."
    exit 0
fi

if [[ "$HAVE_PRIVATE" -eq 1 ]] && [[ "$HAVE_PUBLIC" -eq 1 ]]; then
    info "Private key: OK (${PRIVATE_KEY_PATH})"
    info "Public key header: OK (${PUBLIC_KEY_HPP})"
    info "Nothing to do."
    exit 0
fi

if [[ "$HAVE_PRIVATE" -eq 0 ]] && [[ "$HAVE_PUBLIC" -eq 0 ]]; then
    info "No keys found. Generating new ML-DSA-65 key pair."
    generate_keypair
    write_public_key_hpp
    info "Done. Commit src/build_pubkey.hpp to the repository."
    exit 0
fi

if [[ "$HAVE_PUBLIC" -eq 1 ]] && [[ "$HAVE_PRIVATE" -eq 0 ]]; then
    echo ""
    echo "WARNING: src/build_pubkey.hpp exists but ~/.ntm/privatebuildkey.secret is missing."
    echo "This means the corresponding private key is not available on this machine."
    echo "Generating a NEW key pair will INVALIDATE all existing .sig files."
    echo ""
    read -r -p "Generate a new key pair and overwrite src/build_pubkey.hpp? [y/N] " answer
    if [[ "${answer,,}" != "y" ]]; then
        echo "Aborted."
        exit 1
    fi
    generate_keypair
    write_public_key_hpp
    info "Done. Commit the new src/build_pubkey.hpp to the repository."
    exit 0
fi

if [[ "$HAVE_PRIVATE" -eq 1 ]] && [[ "$HAVE_PUBLIC" -eq 0 ]]; then
    echo ""
    echo "WARNING: Private key found but src/build_pubkey.hpp is missing."
    echo "Regenerating public key header from existing private key."
    echo ""
    read -r -p "Regenerate src/build_pubkey.hpp from existing private key? [y/N] " answer
    if [[ "${answer,,}" != "y" ]]; then
        echo "Aborted."
        exit 1
    fi
    write_public_key_hpp
    info "Done. Commit src/build_pubkey.hpp to the repository."
    exit 0
fi
